language: android

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- platform-tools
    #- tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version fused to compile your project
    - android-23
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-c81a61d9'
      - 'google-gdk-license-.+'

